import type { Metadata } from "next";
import { Geist, Geist_Mono, IBM_Plex_Serif } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { InteractiveCardProvider } from "@/components/ui/interactive-card-context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const ibmPlexSerif = IBM_Plex_Serif({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-ibm-plex-serif",
  display: "swap",
});

const departureMono = localFont({
  src: [
    {
      path: "./fonts/DepartureMono-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/DepartureMono-Regular.woff",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-departure-mono",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${departureMono.variable} ${ibmPlexSerif.variable} antialiased`}
      >
        <InteractiveCardProvider>{children}</InteractiveCardProvider>
      </body>
    </html>
  );
}
